import json

from loguru import logger

from config.settings import OPTIONS_CONFIG
from data_layer.options_data.models import (
    OptionsFactorDefinition,
    OptionsSourceDefinition,
)


def _normalize_filter(values: list[str] | None) -> set[str]:
    return {
        value.strip().lower()
        for value in (values or [])
        if value.strip()
    }


def _split_csv(raw_value: str) -> list[str]:
    return [
        item.strip().upper()
        for item in raw_value.split(",")
        if item.strip()
    ]


def _load_extra_entities() -> list[dict[str, object]]:
    raw_value = OPTIONS_CONFIG.get("extra_entities_json", "").strip()
    if not raw_value:
        return []
    try:
        payload = json.loads(raw_value)
    except json.JSONDecodeError as exc:
        logger.error(f"解析 OPTIONS_EXTRA_ENTITIES_JSON 失败: {exc}")
        return []
    if not isinstance(payload, list):
        logger.error("OPTIONS_EXTRA_ENTITIES_JSON 必须是 JSON 数组")
        return []
    return [dict(item) for item in payload if isinstance(item, dict)]


def _tracked_assets() -> list[str]:
    return _split_csv(OPTIONS_CONFIG["asset_entity_keys"])


def _build_default_options_sources() -> list[OptionsSourceDefinition]:
    return [
        OptionsSourceDefinition(
            source_name="vol_surface",
            name="Options Vol Surface API",
            description="期权隐含波动率曲面标准化接口。",
            collector_key="vol_surface",
            primary_factor_id="options_atm_iv_30d",
            entity_type="asset",
            default_interval=OPTIONS_CONFIG["default_interval"],
            endpoint=OPTIONS_CONFIG["vol_surface_url"] or None,
            enabled=OPTIONS_CONFIG["enable_vol_surface"],
            raw_meta={
                "phase": "P0",
                "semantic_scope": "forward_volatility_pricing",
                "recommended_venues": ["Deribit", "OKX", "Binance"],
            },
        ),
        OptionsSourceDefinition(
            source_name="relative_value",
            name="Options Relative Value API",
            description="期权 IV 与 realized vol 相对定价标准化接口。",
            collector_key="relative_value",
            primary_factor_id="options_iv_rv_spread_30d",
            entity_type="asset",
            default_interval=OPTIONS_CONFIG["default_interval"],
            endpoint=OPTIONS_CONFIG["relative_value_url"] or None,
            enabled=OPTIONS_CONFIG["enable_relative_value"],
            raw_meta={
                "phase": "P0",
                "semantic_scope": "implied_vs_realized_volatility",
                "recommended_venues": ["Deribit", "OKX", "Binance"],
            },
        ),
        OptionsSourceDefinition(
            source_name="strike_concentration",
            name="Options Strike Concentration API",
            description="期权墙位、max pain 与行权价拥挤度标准化接口。",
            collector_key="strike_concentration",
            primary_factor_id="options_top_strike_oi_share",
            entity_type="asset",
            default_interval=OPTIONS_CONFIG["default_interval"],
            endpoint=OPTIONS_CONFIG["strike_concentration_url"] or None,
            enabled=OPTIONS_CONFIG["enable_strike_concentration"],
            raw_meta={
                "phase": "P0",
                "semantic_scope": "strike_wall_and_pin_risk",
                "recommended_venues": ["Deribit", "OKX", "Binance"],
            },
        ),
        OptionsSourceDefinition(
            source_name="gamma_exposure",
            name="Options Gamma Exposure API",
            description="期权 net gamma、gamma flip 与 gamma wall 标准化接口。",
            collector_key="gamma_exposure",
            primary_factor_id="options_net_gamma_exposure_ratio",
            entity_type="asset",
            default_interval=OPTIONS_CONFIG["default_interval"],
            endpoint=OPTIONS_CONFIG["gamma_exposure_url"] or None,
            enabled=OPTIONS_CONFIG["enable_gamma_exposure"],
            raw_meta={
                "phase": "P0",
                "semantic_scope": "dealer_gamma_regime",
                "recommended_venues": ["Deribit", "OKX", "Binance"],
            },
        ),
        OptionsSourceDefinition(
            source_name="flow_activity",
            name="Options Flow Activity API",
            description="期权成交流、开仓意图与 block flow 标准化接口。",
            collector_key="flow_activity",
            primary_factor_id="options_net_call_premium_flow_ratio",
            entity_type="asset",
            default_interval=OPTIONS_CONFIG["default_interval"],
            endpoint=OPTIONS_CONFIG["flow_activity_url"] or None,
            enabled=OPTIONS_CONFIG["enable_flow_activity"],
            raw_meta={
                "phase": "P0",
                "semantic_scope": "incremental_options_flow_intent",
                "recommended_venues": ["Deribit", "OKX", "Binance"],
            },
        ),
        OptionsSourceDefinition(
            source_name="expiry_structure",
            name="Options Expiry Structure API",
            description="期权按到期桶拆分的 OI、gamma 与 premium flow 标准化接口。",
            collector_key="expiry_structure",
            primary_factor_id="options_oi_share_7d",
            entity_type="asset",
            default_interval=OPTIONS_CONFIG["default_interval"],
            endpoint=OPTIONS_CONFIG["expiry_structure_url"] or None,
            enabled=OPTIONS_CONFIG["enable_expiry_structure"],
            raw_meta={
                "phase": "P0",
                "semantic_scope": "expiry_bucket_risk_distribution",
                "recommended_venues": ["Deribit", "OKX", "Binance"],
            },
        ),
        OptionsSourceDefinition(
            source_name="hedge_pressure",
            name="Options Hedge Pressure API",
            description="期权 vanna、charm、volga/vomma、color 与动态对冲压力标准化接口。",
            collector_key="hedge_pressure",
            primary_factor_id="options_vanna_exposure_ratio",
            entity_type="asset",
            default_interval=OPTIONS_CONFIG["default_interval"],
            endpoint=OPTIONS_CONFIG["hedge_pressure_url"] or None,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={
                "phase": "P0",
                "semantic_scope": "dealer_dynamic_hedging_pressure",
                "recommended_venues": ["Deribit", "OKX", "Binance"],
            },
        ),
        OptionsSourceDefinition(
            source_name="positioning",
            name="Options Positioning API",
            description="期权持仓分布与到期结构标准化接口。",
            collector_key="positioning",
            primary_factor_id="options_put_call_oi_ratio_30d",
            entity_type="asset",
            default_interval=OPTIONS_CONFIG["default_interval"],
            endpoint=OPTIONS_CONFIG["positioning_url"] or None,
            enabled=OPTIONS_CONFIG["enable_positioning"],
            raw_meta={
                "phase": "P0",
                "semantic_scope": "open_interest_distribution",
                "recommended_venues": ["Deribit", "OKX", "Binance"],
            },
        ),
    ]


def load_options_sources(
    source_names: list[str] | None = None,
    enabled_only: bool = True,
) -> list[OptionsSourceDefinition]:
    normalized_names = _normalize_filter(source_names)
    selected: list[OptionsSourceDefinition] = []
    for source in _build_default_options_sources():
        if enabled_only and not source.enabled:
            continue
        if normalized_names and source.source_name.lower() not in normalized_names:
            continue
        selected.append(source)
    return selected


def load_options_factors(
    factor_ids: list[str] | None = None,
    source_names: list[str] | None = None,
    enabled_only: bool = True,
) -> list[OptionsFactorDefinition]:
    normalized_factor_ids = _normalize_filter(factor_ids)
    normalized_source_names = _normalize_filter(source_names)
    tracked_assets = _tracked_assets()
    common_meta = {
        "phase": "P0",
        "tracked_assets": tracked_assets,
        "default_interval": OPTIONS_CONFIG["default_interval"],
    }
    definitions = [
        OptionsFactorDefinition(
            factor_id="options_atm_iv_7d",
            name="Options ATM IV 7D",
            category="options_volatility",
            factor_type="implied_volatility",
            entity_scope="asset",
            entity_type="asset",
            description="7 天期限平值隐含波动率。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="vol_surface",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_vol_surface"],
            raw_meta={**common_meta, "tenor": "7d"},
        ),
        OptionsFactorDefinition(
            factor_id="options_atm_iv_30d",
            name="Options ATM IV 30D",
            category="options_volatility",
            factor_type="implied_volatility",
            entity_scope="asset",
            entity_type="asset",
            description="30 天期限平值隐含波动率。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="vol_surface",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_vol_surface"],
            raw_meta={**common_meta, "tenor": "30d"},
        ),
        OptionsFactorDefinition(
            factor_id="options_iv_term_structure_7d_30d",
            name="Options IV Term Structure 7D-30D",
            category="options_volatility",
            factor_type="term_structure_spread",
            entity_scope="asset",
            entity_type="asset",
            description="7 天 ATM IV 减 30 天 ATM IV，用于衡量短端事件风险溢价。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="vol_surface",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_vol_surface"],
            raw_meta={
                **common_meta,
                "front_tenor": "7d",
                "back_tenor": "30d",
                "formula": "atm_iv_7d - atm_iv_30d",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_25d_risk_reversal_30d",
            name="Options 25D Risk Reversal 30D",
            category="options_volatility",
            factor_type="skew",
            entity_scope="asset",
            entity_type="asset",
            description="30 天 25D risk reversal，衡量看涨/看跌偏度。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="vol_surface",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_vol_surface"],
            raw_meta={**common_meta, "tenor": "30d", "delta": "25d"},
        ),
        OptionsFactorDefinition(
            factor_id="options_25d_butterfly_30d",
            name="Options 25D Butterfly 30D",
            category="options_volatility",
            factor_type="convexity",
            entity_scope="asset",
            entity_type="asset",
            description="30 天 25D butterfly，衡量尾部溢价厚度。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="vol_surface",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_vol_surface"],
            raw_meta={**common_meta, "tenor": "30d", "delta": "25d"},
        ),
        OptionsFactorDefinition(
            factor_id="options_realized_vol_7d",
            name="Options Realized Vol 7D",
            category="options_relative_value",
            factor_type="realized_volatility",
            entity_scope="asset",
            entity_type="asset",
            description="过去 7 天已实现波动率。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="relative_value",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_relative_value"],
            raw_meta={**common_meta, "tenor": "7d"},
        ),
        OptionsFactorDefinition(
            factor_id="options_realized_vol_30d",
            name="Options Realized Vol 30D",
            category="options_relative_value",
            factor_type="realized_volatility",
            entity_scope="asset",
            entity_type="asset",
            description="过去 30 天已实现波动率。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="relative_value",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_relative_value"],
            raw_meta={**common_meta, "tenor": "30d"},
        ),
        OptionsFactorDefinition(
            factor_id="options_iv_rv_spread_7d",
            name="Options IV-RV Spread 7D",
            category="options_relative_value",
            factor_type="volatility_spread",
            entity_scope="asset",
            entity_type="asset",
            description="7 天 ATM IV 减 7 天 realized vol。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="relative_value",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_relative_value"],
            raw_meta={
                **common_meta,
                "tenor": "7d",
                "formula": "atm_iv_7d - realized_vol_7d",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_iv_rv_spread_30d",
            name="Options IV-RV Spread 30D",
            category="options_relative_value",
            factor_type="volatility_spread",
            entity_scope="asset",
            entity_type="asset",
            description="30 天 ATM IV 减 30 天 realized vol。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="relative_value",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_relative_value"],
            raw_meta={
                **common_meta,
                "tenor": "30d",
                "formula": "atm_iv_30d - realized_vol_30d",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_max_pain_distance_pct",
            name="Options Max Pain Distance Pct",
            category="options_strike_concentration",
            factor_type="price_distance_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="max pain 价格相对当前现货价格的有符号距离。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="strike_concentration",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_strike_concentration"],
            raw_meta={
                **common_meta,
                "formula": "max_pain_price / spot_price - 1",
                "reference": "spot",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_call_wall_distance_pct",
            name="Options Call Wall Distance Pct",
            category="options_strike_concentration",
            factor_type="price_distance_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="最大 call wall 行权价相对当前现货价格的有符号距离。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="strike_concentration",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_strike_concentration"],
            raw_meta={
                **common_meta,
                "formula": "call_wall_strike / spot_price - 1",
                "reference": "spot",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_put_wall_distance_pct",
            name="Options Put Wall Distance Pct",
            category="options_strike_concentration",
            factor_type="price_distance_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="最大 put wall 行权价相对当前现货价格的有符号距离。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="strike_concentration",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_strike_concentration"],
            raw_meta={
                **common_meta,
                "formula": "put_wall_strike / spot_price - 1",
                "reference": "spot",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_top_strike_oi_share",
            name="Options Top Strike OI Share",
            category="options_strike_concentration",
            factor_type="concentration_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="单一最大行权价的 OI 占全部 OI 比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="strike_concentration",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_strike_concentration"],
            raw_meta={**common_meta, "scope": "all_expiries"},
        ),
        OptionsFactorDefinition(
            factor_id="options_near_expiry_top_strike_oi_share",
            name="Options Near Expiry Top Strike OI Share",
            category="options_strike_concentration",
            factor_type="concentration_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="近到期范围内单一最大行权价的 OI 占近到期 OI 比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="strike_concentration",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_strike_concentration"],
            raw_meta={**common_meta, "scope": "near_expiry"},
        ),
        OptionsFactorDefinition(
            factor_id="options_atm_strike_oi_share",
            name="Options ATM Strike OI Share",
            category="options_strike_concentration",
            factor_type="concentration_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="现货附近 ATM 行权价带的 OI 占全部 OI 比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="strike_concentration",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_strike_concentration"],
            raw_meta={**common_meta, "scope": "atm_band"},
        ),
        OptionsFactorDefinition(
            factor_id="options_net_gamma_exposure",
            name="Options Net Gamma Exposure",
            category="options_gamma_regime",
            factor_type="net_exposure",
            entity_scope="asset",
            entity_type="asset",
            description="dealer net gamma exposure 原始规模。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="usd_per_1pct_move",
            source_name="gamma_exposure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_gamma_exposure"],
            raw_meta={**common_meta, "metric": "net_gamma_exposure"},
        ),
        OptionsFactorDefinition(
            factor_id="options_net_gamma_exposure_ratio",
            name="Options Net Gamma Exposure Ratio",
            category="options_gamma_regime",
            factor_type="share_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="net gamma 相对 gross gamma 的有符号比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="gamma_exposure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_gamma_exposure"],
            raw_meta={
                **common_meta,
                "formula": "net_gamma_exposure / gross_gamma_exposure",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_gamma_flip_distance_pct",
            name="Options Gamma Flip Distance Pct",
            category="options_gamma_regime",
            factor_type="price_distance_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="gamma flip 价格相对当前现货价格的有符号距离。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="gamma_exposure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_gamma_exposure"],
            raw_meta={
                **common_meta,
                "formula": "gamma_flip_price / spot_price - 1",
                "reference": "spot",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_call_gamma_wall_distance_pct",
            name="Options Call Gamma Wall Distance Pct",
            category="options_gamma_regime",
            factor_type="price_distance_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="上方最大 call gamma wall 相对当前现货价格的有符号距离。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="gamma_exposure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_gamma_exposure"],
            raw_meta={
                **common_meta,
                "formula": "call_gamma_wall_strike / spot_price - 1",
                "reference": "spot",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_put_gamma_wall_distance_pct",
            name="Options Put Gamma Wall Distance Pct",
            category="options_gamma_regime",
            factor_type="price_distance_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="下方最大 put gamma wall 相对当前现货价格的有符号距离。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="gamma_exposure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_gamma_exposure"],
            raw_meta={
                **common_meta,
                "formula": "put_gamma_wall_strike / spot_price - 1",
                "reference": "spot",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_top_gamma_strike_share",
            name="Options Top Gamma Strike Share",
            category="options_gamma_regime",
            factor_type="concentration_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="单一最大 gamma strike 占 gross gamma 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="gamma_exposure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_gamma_exposure"],
            raw_meta={**common_meta, "scope": "all_expiries"},
        ),
        OptionsFactorDefinition(
            factor_id="options_near_expiry_gamma_share",
            name="Options Near Expiry Gamma Share",
            category="options_gamma_regime",
            factor_type="concentration_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="近到期 gamma 占 gross gamma 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="gamma_exposure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_gamma_exposure"],
            raw_meta={**common_meta, "scope": "near_expiry"},
        ),
        OptionsFactorDefinition(
            factor_id="options_call_buyer_premium_share",
            name="Options Call Buyer Premium Share",
            category="options_flow_activity",
            factor_type="flow_share",
            entity_scope="asset",
            entity_type="asset",
            description="call buyer-initiated premium 占总 premium 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="flow_activity",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_flow_activity"],
            raw_meta={**common_meta, "flow_side": "call_buy"},
        ),
        OptionsFactorDefinition(
            factor_id="options_put_buyer_premium_share",
            name="Options Put Buyer Premium Share",
            category="options_flow_activity",
            factor_type="flow_share",
            entity_scope="asset",
            entity_type="asset",
            description="put buyer-initiated premium 占总 premium 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="flow_activity",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_flow_activity"],
            raw_meta={**common_meta, "flow_side": "put_buy"},
        ),
        OptionsFactorDefinition(
            factor_id="options_net_call_premium_flow_ratio",
            name="Options Net Call Premium Flow Ratio",
            category="options_flow_activity",
            factor_type="net_flow_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="call buyer premium 减 call seller premium，再除以总 premium。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="flow_activity",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_flow_activity"],
            raw_meta={
                **common_meta,
                "formula": "(call_buyer_premium - call_seller_premium) / total_premium",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_net_put_premium_flow_ratio",
            name="Options Net Put Premium Flow Ratio",
            category="options_flow_activity",
            factor_type="net_flow_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="put buyer premium 减 put seller premium，再除以总 premium。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="flow_activity",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_flow_activity"],
            raw_meta={
                **common_meta,
                "formula": "(put_buyer_premium - put_seller_premium) / total_premium",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_opening_flow_share",
            name="Options Opening Flow Share",
            category="options_flow_activity",
            factor_type="flow_share",
            entity_scope="asset",
            entity_type="asset",
            description="opening premium 占总 premium 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="flow_activity",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_flow_activity"],
            raw_meta={**common_meta, "flow_scope": "opening"},
        ),
        OptionsFactorDefinition(
            factor_id="options_near_expiry_flow_share",
            name="Options Near Expiry Flow Share",
            category="options_flow_activity",
            factor_type="flow_share",
            entity_scope="asset",
            entity_type="asset",
            description="近到期成交 premium 占总 premium 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="flow_activity",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_flow_activity"],
            raw_meta={**common_meta, "flow_scope": "near_expiry"},
        ),
        OptionsFactorDefinition(
            factor_id="options_block_trade_flow_share",
            name="Options Block Trade Flow Share",
            category="options_flow_activity",
            factor_type="flow_share",
            entity_scope="asset",
            entity_type="asset",
            description="block trade premium 占总 premium 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="flow_activity",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_flow_activity"],
            raw_meta={**common_meta, "flow_scope": "block_trade"},
        ),
        OptionsFactorDefinition(
            factor_id="options_oi_share_7d",
            name="Options OI Share 7D",
            category="options_expiry_structure",
            factor_type="expiry_share",
            entity_scope="asset",
            entity_type="asset",
            description="7 天内到期 bucket 的 OI 占全部 OI 比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="expiry_structure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_expiry_structure"],
            raw_meta={**common_meta, "bucket": "7d", "metric": "oi_share"},
        ),
        OptionsFactorDefinition(
            factor_id="options_oi_share_30d",
            name="Options OI Share 30D",
            category="options_expiry_structure",
            factor_type="expiry_share",
            entity_scope="asset",
            entity_type="asset",
            description="30 天内到期 bucket 的 OI 占全部 OI 比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="expiry_structure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_expiry_structure"],
            raw_meta={**common_meta, "bucket": "30d", "metric": "oi_share"},
        ),
        OptionsFactorDefinition(
            factor_id="options_oi_share_90d_plus",
            name="Options OI Share 90D Plus",
            category="options_expiry_structure",
            factor_type="expiry_share",
            entity_scope="asset",
            entity_type="asset",
            description="90 天以上长端 bucket 的 OI 占全部 OI 比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="expiry_structure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_expiry_structure"],
            raw_meta={**common_meta, "bucket": "90d_plus", "metric": "oi_share"},
        ),
        OptionsFactorDefinition(
            factor_id="options_gamma_share_7d",
            name="Options Gamma Share 7D",
            category="options_expiry_structure",
            factor_type="expiry_share",
            entity_scope="asset",
            entity_type="asset",
            description="7 天内到期 bucket 的 gamma 占 gross gamma 比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="expiry_structure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_expiry_structure"],
            raw_meta={**common_meta, "bucket": "7d", "metric": "gamma_share"},
        ),
        OptionsFactorDefinition(
            factor_id="options_gamma_share_30d",
            name="Options Gamma Share 30D",
            category="options_expiry_structure",
            factor_type="expiry_share",
            entity_scope="asset",
            entity_type="asset",
            description="30 天内到期 bucket 的 gamma 占 gross gamma 比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="expiry_structure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_expiry_structure"],
            raw_meta={**common_meta, "bucket": "30d", "metric": "gamma_share"},
        ),
        OptionsFactorDefinition(
            factor_id="options_premium_flow_share_7d",
            name="Options Premium Flow Share 7D",
            category="options_expiry_structure",
            factor_type="expiry_share",
            entity_scope="asset",
            entity_type="asset",
            description="7 天内到期 bucket 的 premium flow 占总 premium 比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="expiry_structure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_expiry_structure"],
            raw_meta={**common_meta, "bucket": "7d", "metric": "premium_flow_share"},
        ),
        OptionsFactorDefinition(
            factor_id="options_premium_flow_share_30d",
            name="Options Premium Flow Share 30D",
            category="options_expiry_structure",
            factor_type="expiry_share",
            entity_scope="asset",
            entity_type="asset",
            description="30 天内到期 bucket 的 premium flow 占总 premium 比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="expiry_structure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_expiry_structure"],
            raw_meta={**common_meta, "bucket": "30d", "metric": "premium_flow_share"},
        ),
        OptionsFactorDefinition(
            factor_id="options_vanna_exposure",
            name="Options Vanna Exposure",
            category="options_hedge_pressure",
            factor_type="cross_greek_exposure",
            entity_scope="asset",
            entity_type="asset",
            description="dealer vanna exposure 原始规模。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="usd_per_1vol_move",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={**common_meta, "metric": "vanna_exposure"},
        ),
        OptionsFactorDefinition(
            factor_id="options_vanna_exposure_ratio",
            name="Options Vanna Exposure Ratio",
            category="options_hedge_pressure",
            factor_type="share_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="vanna exposure 相对 gross gamma 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={
                **common_meta,
                "formula": "vanna_exposure / gross_gamma_exposure",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_charm_exposure",
            name="Options Charm Exposure",
            category="options_hedge_pressure",
            factor_type="time_decay_exposure",
            entity_scope="asset",
            entity_type="asset",
            description="dealer charm exposure 原始规模。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="usd_per_day",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={**common_meta, "metric": "charm_exposure"},
        ),
        OptionsFactorDefinition(
            factor_id="options_charm_exposure_ratio",
            name="Options Charm Exposure Ratio",
            category="options_hedge_pressure",
            factor_type="share_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="charm exposure 相对 gross gamma 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={
                **common_meta,
                "formula": "charm_exposure / gross_gamma_exposure",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_vanna_flip_distance_pct",
            name="Options Vanna Flip Distance Pct",
            category="options_hedge_pressure",
            factor_type="price_distance_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="vanna flip 价格相对当前现货价格的有符号距离。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={
                **common_meta,
                "formula": "vanna_flip_price / spot_price - 1",
                "reference": "spot",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_charm_flip_distance_pct",
            name="Options Charm Flip Distance Pct",
            category="options_hedge_pressure",
            factor_type="price_distance_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="charm flip 价格相对当前现货价格的有符号距离。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={
                **common_meta,
                "formula": "charm_flip_price / spot_price - 1",
                "reference": "spot",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_near_expiry_charm_share",
            name="Options Near Expiry Charm Share",
            category="options_hedge_pressure",
            factor_type="concentration_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="近到期 charm 占总 charm 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={**common_meta, "scope": "near_expiry"},
        ),
        OptionsFactorDefinition(
            factor_id="options_volga_exposure",
            name="Options Volga Exposure",
            category="options_hedge_pressure",
            factor_type="volatility_convexity_exposure",
            entity_scope="asset",
            entity_type="asset",
            description="dealer volga exposure 原始规模。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="usd_per_1vol_squared_move",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={**common_meta, "metric": "volga_exposure"},
        ),
        OptionsFactorDefinition(
            factor_id="options_volga_exposure_ratio",
            name="Options Volga Exposure Ratio",
            category="options_hedge_pressure",
            factor_type="share_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="volga exposure 相对 gross gamma 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={
                **common_meta,
                "formula": "volga_exposure / gross_gamma_exposure",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_vomma_exposure",
            name="Options Vomma Exposure",
            category="options_hedge_pressure",
            factor_type="volatility_convexity_exposure",
            entity_scope="asset",
            entity_type="asset",
            description="dealer vomma exposure 原始规模。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="usd_per_1vol_squared_move",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={**common_meta, "metric": "vomma_exposure"},
        ),
        OptionsFactorDefinition(
            factor_id="options_vomma_exposure_ratio",
            name="Options Vomma Exposure Ratio",
            category="options_hedge_pressure",
            factor_type="share_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="vomma exposure 相对 gross gamma 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={
                **common_meta,
                "formula": "vomma_exposure / gross_gamma_exposure",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_color_exposure",
            name="Options Color Exposure",
            category="options_hedge_pressure",
            factor_type="gamma_decay_exposure",
            entity_scope="asset",
            entity_type="asset",
            description="dealer color exposure 原始规模。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="usd_gamma_per_day",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={**common_meta, "metric": "color_exposure"},
        ),
        OptionsFactorDefinition(
            factor_id="options_color_exposure_ratio",
            name="Options Color Exposure Ratio",
            category="options_hedge_pressure",
            factor_type="share_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="color exposure 相对 gross gamma 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={
                **common_meta,
                "formula": "color_exposure / gross_gamma_exposure",
            },
        ),
        OptionsFactorDefinition(
            factor_id="options_near_expiry_color_share",
            name="Options Near Expiry Color Share",
            category="options_hedge_pressure",
            factor_type="concentration_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="近到期 color 占总 color 的比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="hedge_pressure",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_hedge_pressure"],
            raw_meta={**common_meta, "scope": "near_expiry"},
        ),
        OptionsFactorDefinition(
            factor_id="options_put_call_oi_ratio_30d",
            name="Options Put/Call OI Ratio 30D",
            category="options_positioning",
            factor_type="open_interest_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="30 天期限 put/call OI 名义价值比。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="positioning",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_positioning"],
            raw_meta={**common_meta, "tenor": "30d"},
        ),
        OptionsFactorDefinition(
            factor_id="options_call_oi_share_30d",
            name="Options Call OI Share 30D",
            category="options_positioning",
            factor_type="open_interest_share",
            entity_scope="asset",
            entity_type="asset",
            description="30 天期限 call OI 占总 OI 比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="positioning",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_positioning"],
            raw_meta={**common_meta, "tenor": "30d"},
        ),
        OptionsFactorDefinition(
            factor_id="options_total_oi_notional_30d",
            name="Options Total OI Notional 30D",
            category="options_positioning",
            factor_type="open_interest_notional",
            entity_scope="asset",
            entity_type="asset",
            description="30 天期限总 OI 名义价值。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="usd",
            source_name="positioning",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_positioning"],
            raw_meta={**common_meta, "tenor": "30d"},
        ),
        OptionsFactorDefinition(
            factor_id="options_near_expiry_oi_share",
            name="Options Near Expiry OI Share",
            category="options_positioning",
            factor_type="concentration_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="最近到期 bucket 的 OI 占全期限总 OI 比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="positioning",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_positioning"],
            raw_meta={**common_meta, "scope": "all_expiries"},
        ),
        OptionsFactorDefinition(
            factor_id="options_largest_expiry_oi_share",
            name="Options Largest Expiry OI Share",
            category="options_positioning",
            factor_type="concentration_ratio",
            entity_scope="asset",
            entity_type="asset",
            description="最大单一到期 bucket 的 OI 占全期限总 OI 比例。",
            default_interval=OPTIONS_CONFIG["default_interval"],
            unit="ratio",
            source_name="positioning",
            source_symbol="asset",
            staleness_ttl_seconds=14400,
            enabled=OPTIONS_CONFIG["enable_positioning"],
            raw_meta={**common_meta, "scope": "all_expiries"},
        ),
    ]

    results: list[OptionsFactorDefinition] = []
    for definition in definitions:
        if enabled_only and not definition.enabled:
            continue
        if normalized_factor_ids and definition.factor_id.lower() not in normalized_factor_ids:
            continue
        if normalized_source_names and definition.source_name.lower() not in normalized_source_names:
            continue
        results.append(definition)
    return results


def load_options_entities(
    source_names: list[str] | None = None,
    entity_keys: list[str] | None = None,
) -> list[dict[str, str]]:
    normalized_source_names = _normalize_filter(source_names)
    normalized_entity_keys = {
        value.strip().upper()
        for value in (entity_keys or [])
        if value.strip()
    }
    rows: list[dict[str, str]] = []
    for entity_key in _tracked_assets():
        for source_name in (
            "vol_surface",
            "relative_value",
            "strike_concentration",
            "gamma_exposure",
            "flow_activity",
            "expiry_structure",
            "hedge_pressure",
            "positioning",
        ):
            if normalized_source_names and source_name not in normalized_source_names:
                continue
            if normalized_entity_keys and entity_key not in normalized_entity_keys:
                continue
            rows.append(
                {
                    "source_name": source_name,
                    "entity_type": "asset",
                    "entity_key": entity_key,
                    "name": entity_key,
                    "description": f"{entity_key} 期权市场观察对象",
                }
            )
    for item in _load_extra_entities():
        source_name = str(item.get("source_name") or "").strip().lower()
        entity_key = str(item.get("entity_key") or "").strip().upper()
        if not source_name or not entity_key:
            continue
        if normalized_source_names and source_name not in normalized_source_names:
            continue
        if normalized_entity_keys and entity_key not in normalized_entity_keys:
            continue
        rows.append(
            {
                "source_name": source_name,
                "entity_type": str(item.get("entity_type") or "asset"),
                "entity_key": entity_key,
                "name": str(item.get("name") or entity_key),
                "description": str(item.get("description") or ""),
            }
        )
    return rows
