from config.settings import MACRO_CONFIG
from data_layer.macro_data.models import MacroFactorDefinition


P0_MACRO_FACTORS = [
    MacroFactorDefinition(
        factor_id="dxy",
        name="US Dollar Index",
        category="dollar",
        factor_type="market_price",
        source_kind="yahoo_chart",
        description="美元指数，反映美元相对一篮子货币的强弱。",
        default_interval="1h",
        supported_intervals=["1h", "1d"],
        unit="index_points",
        currency="USD",
        source_name="yahoo_finance",
        source_symbol="DX-Y.NYB",
        market_region="US",
        market_session="us_macro",
        staleness_ttl_seconds=172800,
        is_intraday_enabled=True,
        enabled=True,
    ),
    MacroFactorDefinition(
        factor_id="ust_2y_yield",
        name="US 2Y Treasury Yield",
        category="rates",
        factor_type="macro_level",
        source_kind="fred_csv",
        description="美国 2 年期国债收益率，偏政策预期。",
        default_interval="1d",
        supported_intervals=["1d"],
        unit="percent",
        currency="USD",
        source_name="fred",
        source_symbol="DGS2",
        market_region="US",
        market_session="us_rates",
        staleness_ttl_seconds=604800,
        is_intraday_enabled=False,
        enabled=True,
    ),
    MacroFactorDefinition(
        factor_id="ust_10y_yield",
        name="US 10Y Treasury Yield",
        category="rates",
        factor_type="macro_level",
        source_kind="fred_csv",
        description="美国 10 年期国债收益率，偏增长与通胀预期。",
        default_interval="1d",
        supported_intervals=["1d"],
        unit="percent",
        currency="USD",
        source_name="fred",
        source_symbol="DGS10",
        market_region="US",
        market_session="us_rates",
        staleness_ttl_seconds=604800,
        is_intraday_enabled=False,
        enabled=True,
    ),
    MacroFactorDefinition(
        factor_id="nasdaq_100",
        name="Nasdaq 100",
        category="equity_index",
        factor_type="market_price",
        source_kind="yahoo_chart",
        description="纳斯达克 100 指数，风险偏好主锚。",
        default_interval="1h",
        supported_intervals=["1h", "1d"],
        unit="index_points",
        currency="USD",
        source_name="yahoo_finance",
        source_symbol="^NDX",
        market_region="US",
        market_session="us_equity",
        staleness_ttl_seconds=172800,
        is_intraday_enabled=True,
        enabled=True,
    ),
    MacroFactorDefinition(
        factor_id="gold_spot",
        name="Gold Proxy",
        category="commodity",
        factor_type="market_price",
        source_kind="yahoo_chart",
        description="黄金价格代理，首版使用公开市场可稳定获取的黄金行情近似。",
        default_interval="1h",
        supported_intervals=["1h", "1d"],
        unit="USD/oz",
        currency="USD",
        source_name="yahoo_finance",
        source_symbol="GC=F",
        market_region="global",
        market_session="global_commodity",
        staleness_ttl_seconds=172800,
        is_intraday_enabled=True,
        enabled=True,
    ),
]

P1_MACRO_FACTORS = [
    MacroFactorDefinition(
        factor_id="fed_funds_upper",
        name="Fed Funds Upper Bound",
        category="policy_rate",
        factor_type="macro_level",
        source_kind="fred_csv",
        description="联邦基金目标区间上沿。",
        default_interval="1d",
        supported_intervals=["1d"],
        unit="percent",
        currency="USD",
        source_name="fred",
        source_symbol="DFEDTARU",
        market_region="US",
        market_session="us_rates",
        staleness_ttl_seconds=1209600,
        is_intraday_enabled=False,
        enabled=MACRO_CONFIG["enable_fed_funds_upper"],
    ),
    MacroFactorDefinition(
        factor_id="sp500",
        name="S&P 500",
        category="equity_index",
        factor_type="market_price",
        source_kind="yahoo_chart",
        description="更广义的风险偏好基准。",
        default_interval="1h",
        supported_intervals=["1h", "1d"],
        unit="index_points",
        currency="USD",
        source_name="yahoo_finance",
        source_symbol="^GSPC",
        market_region="US",
        market_session="us_equity",
        staleness_ttl_seconds=172800,
        is_intraday_enabled=True,
        enabled=MACRO_CONFIG["enable_sp500"],
    ),
    MacroFactorDefinition(
        factor_id="vix",
        name="CBOE VIX",
        category="volatility",
        factor_type="market_price",
        source_kind="yahoo_chart",
        description="风险厌恶与波动预期。",
        default_interval="1h",
        supported_intervals=["1h", "1d"],
        unit="index_points",
        currency="USD",
        source_name="yahoo_finance",
        source_symbol="^VIX",
        market_region="US",
        market_session="us_equity",
        staleness_ttl_seconds=172800,
        is_intraday_enabled=True,
        enabled=MACRO_CONFIG["enable_vix"],
    ),
    MacroFactorDefinition(
        factor_id="ust_3m_yield",
        name="US 3M Treasury Yield",
        category="rates",
        factor_type="macro_level",
        source_kind="fred_csv",
        description="美国 3 个月期国债收益率，补足现金收益率和最前端利率锚。",
        default_interval="1d",
        supported_intervals=["1d"],
        unit="percent",
        currency="USD",
        source_name="fred",
        source_symbol="DGS3MO",
        market_region="US",
        market_session="us_rates",
        staleness_ttl_seconds=604800,
        is_intraday_enabled=False,
        enabled=MACRO_CONFIG["enable_ust_3m_yield"],
    ),
    MacroFactorDefinition(
        factor_id="ust_30y_yield",
        name="US 30Y Treasury Yield",
        category="rates",
        factor_type="macro_level",
        source_kind="fred_csv",
        description="美国 30 年期国债收益率。",
        default_interval="1d",
        supported_intervals=["1d"],
        unit="percent",
        currency="USD",
        source_name="fred",
        source_symbol="DGS30",
        market_region="US",
        market_session="us_rates",
        staleness_ttl_seconds=604800,
        is_intraday_enabled=False,
        enabled=MACRO_CONFIG["enable_ust_30y_yield"],
    ),
    MacroFactorDefinition(
        factor_id="ust_10y_real_yield",
        name="US 10Y Real Yield",
        category="real_rates",
        factor_type="macro_level",
        source_kind="fred_csv",
        description="美国 10 年期真实利率，衡量风险资产贴现压力的重要外部锚。",
        default_interval="1d",
        supported_intervals=["1d"],
        unit="percent",
        currency="USD",
        source_name="fred",
        source_symbol="DFII10",
        market_region="US",
        market_session="us_rates",
        staleness_ttl_seconds=604800,
        is_intraday_enabled=False,
        enabled=MACRO_CONFIG["enable_ust_10y_real_yield"],
    ),
    MacroFactorDefinition(
        factor_id="us_10y_breakeven_inflation",
        name="US 10Y Breakeven Inflation",
        category="inflation_expectation",
        factor_type="macro_level",
        source_kind="fred_csv",
        description="美国 10 年期盈亏平衡通胀率，反映市场隐含通胀预期。",
        default_interval="1d",
        supported_intervals=["1d"],
        unit="percent",
        currency="USD",
        source_name="fred",
        source_symbol="T10YIE",
        market_region="US",
        market_session="us_rates",
        staleness_ttl_seconds=604800,
        is_intraday_enabled=False,
        enabled=MACRO_CONFIG["enable_us_10y_breakeven_inflation"],
    ),
    MacroFactorDefinition(
        factor_id="us_bbb_oas",
        name="US BBB OAS",
        category="credit_spread",
        factor_type="macro_level",
        source_kind="fred_csv",
        description="美国 BBB 级公司债期权调整利差，衡量中等级信用风险压力。",
        default_interval="1d",
        supported_intervals=["1d"],
        unit="percent",
        currency="USD",
        source_name="fred",
        source_symbol="BAMLC0A4CBBB",
        market_region="US",
        market_session="us_credit",
        staleness_ttl_seconds=604800,
        is_intraday_enabled=False,
        enabled=MACRO_CONFIG["enable_us_bbb_oas"],
    ),
    MacroFactorDefinition(
        factor_id="us_high_yield_oas",
        name="US High Yield OAS",
        category="credit_spread",
        factor_type="macro_level",
        source_kind="fred_csv",
        description="美国高收益债期权调整利差，衡量风险偏好和信用压力尾部变化。",
        default_interval="1d",
        supported_intervals=["1d"],
        unit="percent",
        currency="USD",
        source_name="fred",
        source_symbol="BAMLH0A0HYM2",
        market_region="US",
        market_session="us_credit",
        staleness_ttl_seconds=604800,
        is_intraday_enabled=False,
        enabled=MACRO_CONFIG["enable_us_high_yield_oas"],
    ),
    MacroFactorDefinition(
        factor_id="wti_crude",
        name="WTI Crude Proxy",
        category="commodity",
        factor_type="market_price",
        source_kind="yahoo_chart",
        description="WTI 原油价格代理。",
        default_interval="1h",
        supported_intervals=["1h", "1d"],
        unit="USD/barrel",
        currency="USD",
        source_name="yahoo_finance",
        source_symbol="CL=F",
        market_region="global",
        market_session="global_commodity",
        staleness_ttl_seconds=172800,
        is_intraday_enabled=True,
        enabled=MACRO_CONFIG["enable_wti_crude"],
    ),
]

ALL_MACRO_FACTORS = [*P0_MACRO_FACTORS, *P1_MACRO_FACTORS]


def load_macro_factors(
    enabled_only: bool = True,
    factor_type: str | None = None,
    factor_ids: list[str] | None = None,
) -> list[MacroFactorDefinition]:
    """加载宏观因子配置。"""

    normalized_ids = {
        factor_id.strip().lower()
        for factor_id in (factor_ids or [])
        if factor_id.strip()
    }
    results: list[MacroFactorDefinition] = []
    for factor in ALL_MACRO_FACTORS:
        if enabled_only and not factor.enabled:
            continue
        if factor_type and factor.factor_type != factor_type:
            continue
        if normalized_ids and factor.factor_id.lower() not in normalized_ids:
            continue
        results.append(factor)
    return results
